version: '2.2'

networks:
  extern:
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
services:

  open3a_db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${OPEN3A_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${OPEN3A_MYSQL_DATABASE}
    volumes:
      - open3a_db:/var/lib/mysql
    networks:
      extern:
        ipv4_address: 172.20.0.3

  open3a-web:
    build: .
    container_name: open3a
    depends_on:
      - open3a_db
    ports:
      - 80:80
    restart: always
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - open3a:/var/www/html
    networks:
      extern:
        ipv4_address: 172.20.0.4

volumes:
  open3a_db:
  open3a: